version: "3.8"
services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      - DATABASE_URL=${SERVER_DATABASE_URL}
    env_file:
      - .env
    ports:
      - "3000:3000"
      - "5555:5555"

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - nextjs
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

volumes:
  postgres_data:
